const NEPAL_CITIES = [
  // ── Koshi Province ──
  { city: "Taplejung",      district: "Taplejung",      lat: 27.35, lon: 87.67, elevation_factor: 8, historical_disaster_index: 7 },
  { city: "Phidim",         district: "Panchthar",      lat: 27.15, lon: 87.77, elevation_factor: 5, historical_disaster_index: 5 },
  { city: "Ilam",           district: "Ilam",           lat: 26.91, lon: 87.92, elevation_factor: 5, historical_disaster_index: 5 },
  { city: "Bhadrapur",      district: "Jhapa",          lat: 26.53, lon: 88.08, elevation_factor: 1, historical_disaster_index: 4 },
  { city: "Birtamod",       district: "Jhapa",          lat: 26.64, lon: 87.99, elevation_factor: 1, historical_disaster_index: 4 },
  { city: "Dhankuta",       district: "Dhankuta",       lat: 26.98, lon: 87.35, elevation_factor: 5, historical_disaster_index: 5 },
  { city: "Biratnagar",     district: "Morang",         lat: 26.45, lon: 87.27, elevation_factor: 1, historical_disaster_index: 5 },
  { city: "Inaruwa",        district: "Sunsari",        lat: 26.57, lon: 87.15, elevation_factor: 1, historical_disaster_index: 4 },
  { city: "Itahari",        district: "Sunsari",        lat: 26.66, lon: 87.27, elevation_factor: 1, historical_disaster_index: 4 },
  { city: "Dharan",         district: "Sunsari",        lat: 26.82, lon: 87.28, elevation_factor: 2, historical_disaster_index: 5 },
  { city: "Khandbari",      district: "Sankhuwasabha",  lat: 27.37, lon: 87.20, elevation_factor: 8, historical_disaster_index: 7 },
  { city: "Bhojpur",        district: "Bhojpur",        lat: 27.17, lon: 87.05, elevation_factor: 5, historical_disaster_index: 5 },
  { city: "Diktel",         district: "Khotang",        lat: 27.22, lon: 86.80, elevation_factor: 5, historical_disaster_index: 5 },
  { city: "Salleri",        district: "Solukhumbu",     lat: 27.50, lon: 86.58, elevation_factor: 8, historical_disaster_index: 7 },
  { city: "Namche Bazaar",  district: "Solukhumbu",     lat: 27.81, lon: 86.71, elevation_factor: 8, historical_disaster_index: 7 },
  { city: "Okhaldhunga",    district: "Okhaldhunga",    lat: 27.31, lon: 86.50, elevation_factor: 5, historical_disaster_index: 5 },
  { city: "Gaighat",        district: "Udayapur",       lat: 26.87, lon: 86.52, elevation_factor: 1, historical_disaster_index: 4 },
  { city: "Rajbiraj",       district: "Saptari",        lat: 26.54, lon: 86.73, elevation_factor: 1, historical_disaster_index: 5 },
  // ── Madhesh Province ──
  { city: "Lahan",          district: "Siraha",         lat: 26.72, lon: 86.48, elevation_factor: 1, historical_disaster_index: 5 },
  { city: "Janakpur",       district: "Dhanusha",       lat: 26.73, lon: 85.93, elevation_factor: 1, historical_disaster_index: 5 },
  { city: "Jaleshwar",      district: "Mahottari",      lat: 26.65, lon: 85.80, elevation_factor: 1, historical_disaster_index: 5 },
  { city: "Malangwa",       district: "Sarlahi",        lat: 26.86, lon: 85.57, elevation_factor: 1, historical_disaster_index: 5 },
  { city: "Kalaiya",        district: "Bara",           lat: 27.03, lon: 85.00, elevation_factor: 1, historical_disaster_index: 4 },
  { city: "Birgunj",        district: "Parsa",          lat: 27.01, lon: 84.88, elevation_factor: 1, historical_disaster_index: 3 },
  { city: "Gaur",           district: "Rautahat",       lat: 26.77, lon: 85.28, elevation_factor: 1, historical_disaster_index: 6 },
  // ── Bagmati Province ──
  { city: "Kathmandu",      district: "Kathmandu",      lat: 27.72, lon: 85.32, elevation_factor: 4, historical_disaster_index: 8 },
  { city: "Lalitpur",       district: "Lalitpur",       lat: 27.66, lon: 85.32, elevation_factor: 4, historical_disaster_index: 7 },
  { city: "Bhaktapur",      district: "Bhaktapur",      lat: 27.67, lon: 85.43, elevation_factor: 4, historical_disaster_index: 7 },
  { city: "Dhulikhel",      district: "Kavrepalanchok", lat: 27.62, lon: 85.55, elevation_factor: 5, historical_disaster_index: 5 },
  { city: "Sindhulimadi",   district: "Sindhuli",       lat: 27.28, lon: 85.97, elevation_factor: 5, historical_disaster_index: 5 },
  { city: "Bharatpur",      district: "Chitwan",        lat: 27.68, lon: 84.43, elevation_factor: 1, historical_disaster_index: 4 },
  { city: "Hetauda",        district: "Makwanpur",      lat: 27.42, lon: 85.03, elevation_factor: 4, historical_disaster_index: 5 },
  { city: "Chautara",       district: "Sindhupalchok",  lat: 27.89, lon: 85.70, elevation_factor: 5, historical_disaster_index: 5 },
  { city: "Charikot",       district: "Dolakha",        lat: 27.67, lon: 86.05, elevation_factor: 5, historical_disaster_index: 5 },
  { city: "Ramechhap",      district: "Ramechhap",      lat: 27.33, lon: 86.09, elevation_factor: 5, historical_disaster_index: 5 },
  { city: "Bidur",          district: "Nuwakot",        lat: 27.90, lon: 85.17, elevation_factor: 5, historical_disaster_index: 5 },
  { city: "Dhading Besi",   district: "Dhading",        lat: 27.87, lon: 84.90, elevation_factor: 5, historical_disaster_index: 5 },
  { city: "Rasuwa",         district: "Rasuwa",         lat: 28.10, lon: 85.37, elevation_factor: 8, historical_disaster_index: 7 },
  // ── Gandaki Province ──
  { city: "Pokhara",        district: "Kaski",          lat: 28.21, lon: 83.99, elevation_factor: 5, historical_disaster_index: 6 },
  { city: "Damauli",        district: "Tanahun",        lat: 27.97, lon: 84.30, elevation_factor: 5, historical_disaster_index: 5 },
  { city: "Waling",         district: "Syangja",        lat: 27.98, lon: 83.78, elevation_factor: 5, historical_disaster_index: 5 },
  { city: "Tansen",         district: "Palpa",          lat: 27.87, lon: 83.55, elevation_factor: 5, historical_disaster_index: 4 },
  { city: "Baglung",        district: "Baglung",        lat: 28.27, lon: 83.58, elevation_factor: 6, historical_disaster_index: 5 },
  { city: "Kusma",          district: "Parbat",         lat: 28.17, lon: 83.72, elevation_factor: 5, historical_disaster_index: 5 },
  { city: "Beni",           district: "Myagdi",         lat: 28.35, lon: 83.57, elevation_factor: 5, historical_disaster_index: 5 },
  { city: "Jomsom",         district: "Mustang",        lat: 28.78, lon: 83.73, elevation_factor: 8, historical_disaster_index: 7 },
  { city: "Chame",          district: "Manang",         lat: 28.55, lon: 84.23, elevation_factor: 8, historical_disaster_index: 7 },
  { city: "Gorkha",         district: "Gorkha",         lat: 28.00, lon: 84.63, elevation_factor: 5, historical_disaster_index: 5 },
  { city: "Besisahar",      district: "Lamjung",        lat: 28.23, lon: 84.42, elevation_factor: 5, historical_disaster_index: 5 },
  { city: "Kawasoti",       district: "Nawalpur",       lat: 27.68, lon: 84.12, elevation_factor: 1, historical_disaster_index: 4 },
  // ── Lumbini Province ──
  { city: "Butwal",         district: "Rupandehi",      lat: 27.70, lon: 83.45, elevation_factor: 2, historical_disaster_index: 4 },
  { city: "Bhairahawa",     district: "Rupandehi",      lat: 27.51, lon: 83.46, elevation_factor: 1, historical_disaster_index: 3 },
  { city: "Ghorahi",        district: "Dang",           lat: 28.03, lon: 82.48, elevation_factor: 2, historical_disaster_index: 4 },
  { city: "Tulsipur",       district: "Dang",           lat: 28.13, lon: 82.30, elevation_factor: 2, historical_disaster_index: 4 },
  { city: "Taulihawa",      district: "Kapilvastu",     lat: 27.55, lon: 83.05, elevation_factor: 1, historical_disaster_index: 4 },
  { city: "Tamghas",        district: "Gulmi",          lat: 28.08, lon: 83.28, elevation_factor: 5, historical_disaster_index: 5 },
  { city: "Musikot",        district: "Rukum",          lat: 28.63, lon: 82.52, elevation_factor: 5, historical_disaster_index: 5 },
  { city: "Salyan",         district: "Salyan",         lat: 28.37, lon: 82.17, elevation_factor: 5, historical_disaster_index: 5 },
  { city: "Pyuthan",        district: "Pyuthan",        lat: 28.10, lon: 82.85, elevation_factor: 5, historical_disaster_index: 5 },
  { city: "Rolpa",          district: "Rolpa",          lat: 28.32, lon: 82.63, elevation_factor: 5, historical_disaster_index: 5 },
  // ── Karnali Province ──
  { city: "Birendranagar",  district: "Surkhet",        lat: 28.60, lon: 81.63, elevation_factor: 5, historical_disaster_index: 5 },
  { city: "Jumla",          district: "Jumla",          lat: 29.27, lon: 82.18, elevation_factor: 8, historical_disaster_index: 7 },
  { city: "Gamgadhi",       district: "Mugu",           lat: 29.53, lon: 82.57, elevation_factor: 8, historical_disaster_index: 7 },
  { city: "Dunai",          district: "Dolpa",          lat: 28.92, lon: 82.90, elevation_factor: 8, historical_disaster_index: 7 },
  { city: "Manma",          district: "Kalikot",        lat: 29.15, lon: 81.72, elevation_factor: 8, historical_disaster_index: 7 },
  { city: "Dailekh",        district: "Dailekh",        lat: 28.84, lon: 81.72, elevation_factor: 5, historical_disaster_index: 6 },
  { city: "Jajarkot",       district: "Jajarkot",       lat: 28.70, lon: 82.18, elevation_factor: 5, historical_disaster_index: 5 },
  { city: "Simikot",        district: "Humla",          lat: 29.97, lon: 81.82, elevation_factor: 8, historical_disaster_index: 7 },
  // ── Sudurpashchim Province ──
  { city: "Dhangadhi",      district: "Kailali",        lat: 28.69, lon: 80.59, elevation_factor: 1, historical_disaster_index: 5 },
  { city: "Tikapur",        district: "Kailali",        lat: 28.52, lon: 81.12, elevation_factor: 1, historical_disaster_index: 4 },
  { city: "Mahendranagar",  district: "Kanchanpur",     lat: 28.97, lon: 80.18, elevation_factor: 1, historical_disaster_index: 4 },
  { city: "Nepalgunj",      district: "Banke",          lat: 28.05, lon: 81.62, elevation_factor: 1, historical_disaster_index: 4 },
  { city: "Gulariya",       district: "Bardiya",        lat: 28.18, lon: 81.50, elevation_factor: 1, historical_disaster_index: 6 },
  { city: "Martadi",        district: "Bajura",         lat: 29.53, lon: 81.57, elevation_factor: 8, historical_disaster_index: 7 },
  { city: "Chainpur",       district: "Bajhang",        lat: 29.55, lon: 81.18, elevation_factor: 8, historical_disaster_index: 7 },
  { city: "Darchula",       district: "Darchula",       lat: 29.85, lon: 80.55, elevation_factor: 8, historical_disaster_index: 7 },
  { city: "Dipayal",        district: "Doti",           lat: 29.27, lon: 80.95, elevation_factor: 5, historical_disaster_index: 5 },
  { city: "Sanfebagar",     district: "Achham",         lat: 29.08, lon: 81.16, elevation_factor: 5, historical_disaster_index: 5 },
  { city: "Baitadi",        district: "Baitadi",        lat: 29.55, lon: 80.42, elevation_factor: 5, historical_disaster_index: 5 },
  { city: "Dadeldhura",     district: "Dadeldhura",     lat: 29.30, lon: 80.58, elevation_factor: 5, historical_disaster_index: 5 },
];

module.exports = NEPAL_CITIES;

